"""Tabela de membros convidados

Revision ID: 55829a3ad972
Revises: 222bef97df40
Create Date: 2025-05-09 17:39:35.285863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55829a3ad972'
down_revision: Union[str, None] = '222bef97df40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('versao_ata_reuniao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('versao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_versao_ata_reuniao_id'), 'versao_ata_reuniao', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_versao_ata_reuniao_id'), table_name='versao_ata_reuniao')
    op.drop_table('versao_ata_reuniao')
    # ### end Alembic commands ###
